-- 0116_seed_bd_locations.sql
-- Seeds the location hierarchy (0003) with the official division/district/
-- upazila tree, sourced from the community-maintained, MIT-licensed
-- https://github.com/ifahimreza/bangladesh-geojson reference data (8
-- divisions, 64 districts, 492 upazilas — deduped from 494 source rows: the
-- upstream bd-upazilas.json lists "Natore Sadar" and "Baraigram" twice each
-- under Natore district). Idempotent — every insert is guarded by a
-- `where not exists` on (type, name, parent), so it's safe to run against a
-- database that already has manually-entered locations (including the
-- "Staging Division" placeholder from staging-seed.sql) or to re-run.
--
-- The source data stops at upazila — it has no union level, so the tree's
-- 4th tier (union) is left exactly as-is, still entered manually via the
-- super-admin Locations page (web/app/super-admin/locations).

insert into public.locations (name, type, parent_id)
select v.name, 'division', null
from (values
  ('Barishal'),
  ('Chattogram'),
  ('Dhaka'),
  ('Khulna'),
  ('Rajshahi'),
  ('Rangpur'),
  ('Sylhet'),
  ('Mymensingh')
) as v(name)
where not exists (
  select 1 from public.locations l where l.type = 'division' and l.name = v.name
);

insert into public.locations (name, type, parent_id)
select v.name, 'district', d.id
from (values
  ('Dhaka', 'Dhaka'),
  ('Faridpur', 'Dhaka'),
  ('Gazipur', 'Dhaka'),
  ('Gopalganj', 'Dhaka'),
  ('Jamalpur', 'Mymensingh'),
  ('Kishoreganj', 'Dhaka'),
  ('Madaripur', 'Dhaka'),
  ('Manikganj', 'Dhaka'),
  ('Munshiganj', 'Dhaka'),
  ('Mymensingh', 'Mymensingh'),
  ('Narayanganj', 'Dhaka'),
  ('Narsingdi', 'Dhaka'),
  ('Netrokona', 'Mymensingh'),
  ('Rajbari', 'Dhaka'),
  ('Shariatpur', 'Dhaka'),
  ('Sherpur', 'Mymensingh'),
  ('Tangail', 'Dhaka'),
  ('Bogura', 'Rajshahi'),
  ('Joypurhat', 'Rajshahi'),
  ('Naogaon', 'Rajshahi'),
  ('Natore', 'Rajshahi'),
  ('Nawabganj', 'Rajshahi'),
  ('Pabna', 'Rajshahi'),
  ('Rajshahi', 'Rajshahi'),
  ('Sirajgonj', 'Rajshahi'),
  ('Dinajpur', 'Rangpur'),
  ('Gaibandha', 'Rangpur'),
  ('Kurigram', 'Rangpur'),
  ('Lalmonirhat', 'Rangpur'),
  ('Nilphamari', 'Rangpur'),
  ('Panchagarh', 'Rangpur'),
  ('Rangpur', 'Rangpur'),
  ('Thakurgaon', 'Rangpur'),
  ('Barguna', 'Barishal'),
  ('Barishal', 'Barishal'),
  ('Bhola', 'Barishal'),
  ('Jhalokati', 'Barishal'),
  ('Patuakhali', 'Barishal'),
  ('Pirojpur', 'Barishal'),
  ('Bandarban', 'Chattogram'),
  ('Brahmanbaria', 'Chattogram'),
  ('Chandpur', 'Chattogram'),
  ('Chattogram', 'Chattogram'),
  ('Cumilla', 'Chattogram'),
  ('Cox''s Bazar', 'Chattogram'),
  ('Feni', 'Chattogram'),
  ('Khagrachari', 'Chattogram'),
  ('Lakshmipur', 'Chattogram'),
  ('Noakhali', 'Chattogram'),
  ('Rangamati', 'Chattogram'),
  ('Habiganj', 'Sylhet'),
  ('Maulvibazar', 'Sylhet'),
  ('Sunamganj', 'Sylhet'),
  ('Sylhet', 'Sylhet'),
  ('Bagerhat', 'Khulna'),
  ('Chuadanga', 'Khulna'),
  ('Jashore', 'Khulna'),
  ('Jhenaidah', 'Khulna'),
  ('Khulna', 'Khulna'),
  ('Kushtia', 'Khulna'),
  ('Magura', 'Khulna'),
  ('Meherpur', 'Khulna'),
  ('Narail', 'Khulna'),
  ('Satkhira', 'Khulna')
) as v(name, division_name)
join public.locations d on d.type = 'division' and d.name = v.division_name
where not exists (
  select 1 from public.locations l where l.type = 'district' and l.name = v.name and l.parent_id = d.id
);

insert into public.locations (name, type, parent_id)
select v.name, 'upazila', dd.id
from (values
  ('Amtali', 'Barguna'),
  ('Bamna', 'Barguna'),
  ('Barguna Sadar', 'Barguna'),
  ('Betagi', 'Barguna'),
  ('Patharghata', 'Barguna'),
  ('Taltali', 'Barguna'),
  ('Muladi', 'Barishal'),
  ('Babuganj', 'Barishal'),
  ('Agailjhara', 'Barishal'),
  ('Barisal Sadar', 'Barishal'),
  ('Bakerganj', 'Barishal'),
  ('Banaripara', 'Barishal'),
  ('Gaurnadi', 'Barishal'),
  ('Hizla', 'Barishal'),
  ('Mehendiganj', 'Barishal'),
  ('Wazirpur', 'Barishal'),
  ('Bhola Sadar', 'Bhola'),
  ('Burhanuddin', 'Bhola'),
  ('Char Fasson', 'Bhola'),
  ('Daulatkhan', 'Bhola'),
  ('Lalmohan', 'Bhola'),
  ('Manpura', 'Bhola'),
  ('Tazumuddin', 'Bhola'),
  ('Jhalokati Sadar', 'Jhalokati'),
  ('Kathalia', 'Jhalokati'),
  ('Nalchity', 'Jhalokati'),
  ('Rajapur', 'Jhalokati'),
  ('Bauphal', 'Patuakhali'),
  ('Dashmina', 'Patuakhali'),
  ('Galachipa', 'Patuakhali'),
  ('Kalapara', 'Patuakhali'),
  ('Mirzaganj', 'Patuakhali'),
  ('Patuakhali Sadar', 'Patuakhali'),
  ('Dumki', 'Patuakhali'),
  ('Rangabali', 'Patuakhali'),
  ('Bhandaria', 'Pirojpur'),
  ('Kaukhali', 'Pirojpur'),
  ('Mathbaria', 'Pirojpur'),
  ('Nazirpur', 'Pirojpur'),
  ('Nesarabad', 'Pirojpur'),
  ('Pirojpur Sadar', 'Pirojpur'),
  ('Zianagar', 'Pirojpur'),
  ('Bandarban Sadar', 'Bandarban'),
  ('Thanchi', 'Bandarban'),
  ('Lama', 'Bandarban'),
  ('Naikhongchhari', 'Bandarban'),
  ('Ali kadam', 'Bandarban'),
  ('Rowangchhari', 'Bandarban'),
  ('Ruma', 'Bandarban'),
  ('Brahmanbaria Sadar', 'Brahmanbaria'),
  ('Ashuganj', 'Brahmanbaria'),
  ('Nasirnagar', 'Brahmanbaria'),
  ('Nabinagar', 'Brahmanbaria'),
  ('Sarail', 'Brahmanbaria'),
  ('Shahbazpur Town', 'Brahmanbaria'),
  ('Kasba', 'Brahmanbaria'),
  ('Akhaura', 'Brahmanbaria'),
  ('Bancharampur', 'Brahmanbaria'),
  ('Bijoynagar', 'Brahmanbaria'),
  ('Chandpur Sadar', 'Chandpur'),
  ('Faridganj', 'Chandpur'),
  ('Haimchar', 'Chandpur'),
  ('Haziganj', 'Chandpur'),
  ('Kachua', 'Chandpur'),
  ('Matlab Uttar', 'Chandpur'),
  ('Matlab Dakkhin', 'Chandpur'),
  ('Shahrasti', 'Chandpur'),
  ('Anwara', 'Chattogram'),
  ('Banshkhali', 'Chattogram'),
  ('Boalkhali', 'Chattogram'),
  ('Chandanaish', 'Chattogram'),
  ('Fatikchhari', 'Chattogram'),
  ('Hathazari', 'Chattogram'),
  ('Lohagara', 'Chattogram'),
  ('Mirsharai', 'Chattogram'),
  ('Patiya', 'Chattogram'),
  ('Rangunia', 'Chattogram'),
  ('Raozan', 'Chattogram'),
  ('Sandwip', 'Chattogram'),
  ('Satkania', 'Chattogram'),
  ('Sitakunda', 'Chattogram'),
  ('Barura', 'Cumilla'),
  ('Brahmanpara', 'Cumilla'),
  ('Burichong', 'Cumilla'),
  ('Chandina', 'Cumilla'),
  ('Chauddagram', 'Cumilla'),
  ('Daudkandi', 'Cumilla'),
  ('Debidwar', 'Cumilla'),
  ('Homna', 'Cumilla'),
  ('Comilla Sadar', 'Cumilla'),
  ('Laksam', 'Cumilla'),
  ('Monohorgonj', 'Cumilla'),
  ('Meghna', 'Cumilla'),
  ('Muradnagar', 'Cumilla'),
  ('Nangalkot', 'Cumilla'),
  ('Comilla Sadar South', 'Cumilla'),
  ('Titas', 'Cumilla'),
  ('Chakaria', 'Cox''s Bazar'),
  ('Cox''s Bazar Sadar', 'Cox''s Bazar'),
  ('Kutubdia', 'Cox''s Bazar'),
  ('Maheshkhali', 'Cox''s Bazar'),
  ('Ramu', 'Cox''s Bazar'),
  ('Teknaf', 'Cox''s Bazar'),
  ('Ukhia', 'Cox''s Bazar'),
  ('Pekua', 'Cox''s Bazar'),
  ('Feni Sadar', 'Feni'),
  ('Chagalnaiya', 'Feni'),
  ('Daganbhyan', 'Feni'),
  ('Parshuram', 'Feni'),
  ('Fhulgazi', 'Feni'),
  ('Sonagazi', 'Feni'),
  ('Dighinala', 'Khagrachari'),
  ('Khagrachhari', 'Khagrachari'),
  ('Lakshmichhari', 'Khagrachari'),
  ('Mahalchhari', 'Khagrachari'),
  ('Manikchhari', 'Khagrachari'),
  ('Matiranga', 'Khagrachari'),
  ('Panchhari', 'Khagrachari'),
  ('Ramgarh', 'Khagrachari'),
  ('Lakshmipur Sadar', 'Lakshmipur'),
  ('Raipur', 'Lakshmipur'),
  ('Ramganj', 'Lakshmipur'),
  ('Ramgati', 'Lakshmipur'),
  ('Komol Nagar', 'Lakshmipur'),
  ('Noakhali Sadar', 'Noakhali'),
  ('Begumganj', 'Noakhali'),
  ('Chatkhil', 'Noakhali'),
  ('Companyganj', 'Noakhali'),
  ('Shenbag', 'Noakhali'),
  ('Hatia', 'Noakhali'),
  ('Kobirhat', 'Noakhali'),
  ('Sonaimuri', 'Noakhali'),
  ('Suborno Char', 'Noakhali'),
  ('Rangamati Sadar', 'Rangamati'),
  ('Belaichhari', 'Rangamati'),
  ('Bagaichhari', 'Rangamati'),
  ('Barkal', 'Rangamati'),
  ('Juraichhari', 'Rangamati'),
  ('Rajasthali', 'Rangamati'),
  ('Kaptai', 'Rangamati'),
  ('Langadu', 'Rangamati'),
  ('Nannerchar', 'Rangamati'),
  ('Kaukhali', 'Rangamati'),
  ('Dhamrai', 'Dhaka'),
  ('Dohar', 'Dhaka'),
  ('Keraniganj', 'Dhaka'),
  ('Nawabganj', 'Dhaka'),
  ('Savar', 'Dhaka'),
  ('Faridpur Sadar', 'Faridpur'),
  ('Boalmari', 'Faridpur'),
  ('Alfadanga', 'Faridpur'),
  ('Madhukhali', 'Faridpur'),
  ('Bhanga', 'Faridpur'),
  ('Nagarkanda', 'Faridpur'),
  ('Charbhadrasan', 'Faridpur'),
  ('Sadarpur', 'Faridpur'),
  ('Shaltha', 'Faridpur'),
  ('Gazipur Sadar', 'Gazipur'),
  ('Kaliakior', 'Gazipur'),
  ('Kapasia', 'Gazipur'),
  ('Sripur', 'Gazipur'),
  ('Kaliganj', 'Gazipur'),
  ('Tongi', 'Gazipur'),
  ('Gopalganj Sadar', 'Gopalganj'),
  ('Kashiani', 'Gopalganj'),
  ('Kotalipara', 'Gopalganj'),
  ('Muksudpur', 'Gopalganj'),
  ('Tungipara', 'Gopalganj'),
  ('Dewanganj', 'Jamalpur'),
  ('Baksiganj', 'Jamalpur'),
  ('Islampur', 'Jamalpur'),
  ('Jamalpur Sadar', 'Jamalpur'),
  ('Madarganj', 'Jamalpur'),
  ('Melandaha', 'Jamalpur'),
  ('Sarishabari', 'Jamalpur'),
  ('Narundi Police I.C', 'Jamalpur'),
  ('Astagram', 'Kishoreganj'),
  ('Bajitpur', 'Kishoreganj'),
  ('Bhairab', 'Kishoreganj'),
  ('Hossainpur', 'Kishoreganj'),
  ('Itna', 'Kishoreganj'),
  ('Karimganj', 'Kishoreganj'),
  ('Katiadi', 'Kishoreganj'),
  ('Kishoreganj Sadar', 'Kishoreganj'),
  ('Kuliarchar', 'Kishoreganj'),
  ('Mithamain', 'Kishoreganj'),
  ('Nikli', 'Kishoreganj'),
  ('Pakundia', 'Kishoreganj'),
  ('Tarail', 'Kishoreganj'),
  ('Madaripur Sadar', 'Madaripur'),
  ('Kalkini', 'Madaripur'),
  ('Rajoir', 'Madaripur'),
  ('Shibchar', 'Madaripur'),
  ('Manikganj Sadar', 'Manikganj'),
  ('Singair', 'Manikganj'),
  ('Shibalaya', 'Manikganj'),
  ('Saturia', 'Manikganj'),
  ('Harirampur', 'Manikganj'),
  ('Ghior', 'Manikganj'),
  ('Daulatpur', 'Manikganj'),
  ('Lohajang', 'Munshiganj'),
  ('Sreenagar', 'Munshiganj'),
  ('Munshiganj Sadar', 'Munshiganj'),
  ('Sirajdikhan', 'Munshiganj'),
  ('Tongibari', 'Munshiganj'),
  ('Gazaria', 'Munshiganj'),
  ('Bhaluka', 'Mymensingh'),
  ('Trishal', 'Mymensingh'),
  ('Haluaghat', 'Mymensingh'),
  ('Muktagachha', 'Mymensingh'),
  ('Dhobaura', 'Mymensingh'),
  ('Fulbaria', 'Mymensingh'),
  ('Gaffargaon', 'Mymensingh'),
  ('Gauripur', 'Mymensingh'),
  ('Ishwarganj', 'Mymensingh'),
  ('Mymensingh Sadar', 'Mymensingh'),
  ('Nandail', 'Mymensingh'),
  ('Phulpur', 'Mymensingh'),
  ('Araihazar', 'Narayanganj'),
  ('Sonargaon', 'Narayanganj'),
  ('Bandar', 'Narayanganj'),
  ('Narayanganj Sadar', 'Narayanganj'),
  ('Rupganj', 'Narayanganj'),
  ('Siddhirganj', 'Narayanganj'),
  ('Belabo', 'Narsingdi'),
  ('Monohardi', 'Narsingdi'),
  ('Narsingdi Sadar', 'Narsingdi'),
  ('Palash', 'Narsingdi'),
  ('Raipura, Narsingdi', 'Narsingdi'),
  ('Shibpur', 'Narsingdi'),
  ('Kendua', 'Netrokona'),
  ('Atpara', 'Netrokona'),
  ('Barhatta', 'Netrokona'),
  ('Durgapur', 'Netrokona'),
  ('Kalmakanda', 'Netrokona'),
  ('Madan', 'Netrokona'),
  ('Mohanganj', 'Netrokona'),
  ('Netrokona Sadar', 'Netrokona'),
  ('Purbadhala', 'Netrokona'),
  ('Khaliajuri', 'Netrokona'),
  ('Baliakandi', 'Rajbari'),
  ('Goalandaghat', 'Rajbari'),
  ('Pangsha', 'Rajbari'),
  ('Kalukhali', 'Rajbari'),
  ('Rajbari Sadar', 'Rajbari'),
  ('Shariatpur Sadar', 'Shariatpur'),
  ('Damudya', 'Shariatpur'),
  ('Naria', 'Shariatpur'),
  ('Jajira', 'Shariatpur'),
  ('Bhedarganj', 'Shariatpur'),
  ('Gosairhat', 'Shariatpur'),
  ('Jhenaigati', 'Sherpur'),
  ('Nakla', 'Sherpur'),
  ('Nalitabari', 'Sherpur'),
  ('Sherpur Sadar', 'Sherpur'),
  ('Sreebardi', 'Sherpur'),
  ('Tangail Sadar', 'Tangail'),
  ('Sakhipur', 'Tangail'),
  ('Basail', 'Tangail'),
  ('Madhupur', 'Tangail'),
  ('Ghatail', 'Tangail'),
  ('Kalihati', 'Tangail'),
  ('Nagarpur', 'Tangail'),
  ('Mirzapur', 'Tangail'),
  ('Gopalpur', 'Tangail'),
  ('Delduar', 'Tangail'),
  ('Bhuapur', 'Tangail'),
  ('Dhanbari', 'Tangail'),
  ('Bagerhat Sadar', 'Bagerhat'),
  ('Chitalmari', 'Bagerhat'),
  ('Fakirhat', 'Bagerhat'),
  ('Kachua', 'Bagerhat'),
  ('Mollahat', 'Bagerhat'),
  ('Mongla', 'Bagerhat'),
  ('Morrelganj', 'Bagerhat'),
  ('Rampal', 'Bagerhat'),
  ('Sarankhola', 'Bagerhat'),
  ('Damurhuda', 'Chuadanga'),
  ('Chuadanga Sadar', 'Chuadanga'),
  ('Jibannagar', 'Chuadanga'),
  ('Alamdanga', 'Chuadanga'),
  ('Abhaynagar', 'Jashore'),
  ('Keshabpur', 'Jashore'),
  ('Bagherpara', 'Jashore'),
  ('Jessore Sadar', 'Jashore'),
  ('Chaugachha', 'Jashore'),
  ('Manirampur', 'Jashore'),
  ('Jhikargachha', 'Jashore'),
  ('Sharsha', 'Jashore'),
  ('Jhenaidah Sadar', 'Jhenaidah'),
  ('Maheshpur', 'Jhenaidah'),
  ('Kaliganj', 'Jhenaidah'),
  ('Kotchandpur', 'Jhenaidah'),
  ('Shailkupa', 'Jhenaidah'),
  ('Harinakunda', 'Jhenaidah'),
  ('Terokhada', 'Khulna'),
  ('Batiaghata', 'Khulna'),
  ('Dacope', 'Khulna'),
  ('Dumuria', 'Khulna'),
  ('Dighalia', 'Khulna'),
  ('Koyra', 'Khulna'),
  ('Paikgachha', 'Khulna'),
  ('Phultala', 'Khulna'),
  ('Rupsa', 'Khulna'),
  ('Kushtia Sadar', 'Kushtia'),
  ('Kumarkhali', 'Kushtia'),
  ('Daulatpur', 'Kushtia'),
  ('Mirpur', 'Kushtia'),
  ('Bheramara', 'Kushtia'),
  ('Khoksa', 'Kushtia'),
  ('Magura Sadar', 'Magura'),
  ('Mohammadpur', 'Magura'),
  ('Shalikha', 'Magura'),
  ('Sreepur', 'Magura'),
  ('Gangni', 'Meherpur'),
  ('Mujib Nagar', 'Meherpur'),
  ('Meherpur Sadar', 'Meherpur'),
  ('Narail Sadar', 'Narail'),
  ('Lohagara', 'Narail'),
  ('Kalia', 'Narail'),
  ('Satkhira Sadar', 'Satkhira'),
  ('Assasuni', 'Satkhira'),
  ('Debhata', 'Satkhira'),
  ('Tala', 'Satkhira'),
  ('Kalaroa', 'Satkhira'),
  ('Kaliganj', 'Satkhira'),
  ('Shyamnagar', 'Satkhira'),
  ('Adamdighi', 'Bogura'),
  ('Bogra Sadar', 'Bogura'),
  ('Sherpur', 'Bogura'),
  ('Dhunat', 'Bogura'),
  ('Dhupchanchia', 'Bogura'),
  ('Gabtali', 'Bogura'),
  ('Kahaloo', 'Bogura'),
  ('Nandigram', 'Bogura'),
  ('Sahajanpur', 'Bogura'),
  ('Sariakandi', 'Bogura'),
  ('Shibganj', 'Bogura'),
  ('Sonatala', 'Bogura'),
  ('Joypurhat Sadar', 'Joypurhat'),
  ('Akkelpur', 'Joypurhat'),
  ('Kalai', 'Joypurhat'),
  ('Khetlal', 'Joypurhat'),
  ('Panchbibi', 'Joypurhat'),
  ('Naogaon Sadar', 'Naogaon'),
  ('Mohadevpur', 'Naogaon'),
  ('Manda', 'Naogaon'),
  ('Niamatpur', 'Naogaon'),
  ('Atrai', 'Naogaon'),
  ('Raninagar', 'Naogaon'),
  ('Patnitala', 'Naogaon'),
  ('Dhamoirhat', 'Naogaon'),
  ('Sapahar', 'Naogaon'),
  ('Porsha', 'Naogaon'),
  ('Badalgachhi', 'Naogaon'),
  ('Natore Sadar', 'Natore'),
  ('Baraigram', 'Natore'),
  ('Bagatipara', 'Natore'),
  ('Lalpur', 'Natore'),
  ('Bholahat', 'Nawabganj'),
  ('Gomastapur', 'Nawabganj'),
  ('Nachole', 'Nawabganj'),
  ('Nawabganj Sadar', 'Nawabganj'),
  ('Shibganj', 'Nawabganj'),
  ('Atgharia', 'Pabna'),
  ('Bera', 'Pabna'),
  ('Bhangura', 'Pabna'),
  ('Chatmohar', 'Pabna'),
  ('Faridpur', 'Pabna'),
  ('Ishwardi', 'Pabna'),
  ('Pabna Sadar', 'Pabna'),
  ('Santhia', 'Pabna'),
  ('Sujanagar', 'Pabna'),
  ('Bagha', 'Rajshahi'),
  ('Bagmara', 'Rajshahi'),
  ('Charghat', 'Rajshahi'),
  ('Durgapur', 'Rajshahi'),
  ('Godagari', 'Rajshahi'),
  ('Mohanpur', 'Rajshahi'),
  ('Paba', 'Rajshahi'),
  ('Puthia', 'Rajshahi'),
  ('Tanore', 'Rajshahi'),
  ('Sirajganj Sadar', 'Sirajgonj'),
  ('Belkuchi', 'Sirajgonj'),
  ('Chauhali', 'Sirajgonj'),
  ('Kamarkhanda', 'Sirajgonj'),
  ('Kazipur', 'Sirajgonj'),
  ('Raiganj', 'Sirajgonj'),
  ('Shahjadpur', 'Sirajgonj'),
  ('Tarash', 'Sirajgonj'),
  ('Ullahpara', 'Sirajgonj'),
  ('Birampur', 'Dinajpur'),
  ('Birganj', 'Dinajpur'),
  ('Biral', 'Dinajpur'),
  ('Bochaganj', 'Dinajpur'),
  ('Chirirbandar', 'Dinajpur'),
  ('Phulbari', 'Dinajpur'),
  ('Ghoraghat', 'Dinajpur'),
  ('Hakimpur', 'Dinajpur'),
  ('Kaharole', 'Dinajpur'),
  ('Khansama', 'Dinajpur'),
  ('Dinajpur Sadar', 'Dinajpur'),
  ('Nawabganj', 'Dinajpur'),
  ('Parbatipur', 'Dinajpur'),
  ('Fulchhari', 'Gaibandha'),
  ('Gaibandha Sadar', 'Gaibandha'),
  ('Gobindaganj', 'Gaibandha'),
  ('Palashbari', 'Gaibandha'),
  ('Sadullapur', 'Gaibandha'),
  ('Saghata', 'Gaibandha'),
  ('Sundarganj', 'Gaibandha'),
  ('Kurigram Sadar', 'Kurigram'),
  ('Nageshwari', 'Kurigram'),
  ('Bhurungamari', 'Kurigram'),
  ('Phulbari', 'Kurigram'),
  ('Rajarhat', 'Kurigram'),
  ('Ulipur', 'Kurigram'),
  ('Chilmari', 'Kurigram'),
  ('Rowmari', 'Kurigram'),
  ('Char Rajibpur', 'Kurigram'),
  ('Lalmanirhat Sadar', 'Lalmonirhat'),
  ('Aditmari', 'Lalmonirhat'),
  ('Kaliganj', 'Lalmonirhat'),
  ('Hatibandha', 'Lalmonirhat'),
  ('Patgram', 'Lalmonirhat'),
  ('Nilphamari Sadar', 'Nilphamari'),
  ('Saidpur', 'Nilphamari'),
  ('Jaldhaka', 'Nilphamari'),
  ('Kishoreganj', 'Nilphamari'),
  ('Domar', 'Nilphamari'),
  ('Dimla', 'Nilphamari'),
  ('Panchagarh Sadar', 'Panchagarh'),
  ('Debiganj', 'Panchagarh'),
  ('Boda', 'Panchagarh'),
  ('Atwari', 'Panchagarh'),
  ('Tetulia', 'Panchagarh'),
  ('Badarganj', 'Rangpur'),
  ('Mithapukur', 'Rangpur'),
  ('Gangachara', 'Rangpur'),
  ('Kaunia', 'Rangpur'),
  ('Rangpur Sadar', 'Rangpur'),
  ('Pirgachha', 'Rangpur'),
  ('Pirganj', 'Rangpur'),
  ('Taraganj', 'Rangpur'),
  ('Thakurgaon Sadar', 'Thakurgaon'),
  ('Pirganj', 'Thakurgaon'),
  ('Baliadangi', 'Thakurgaon'),
  ('Haripur', 'Thakurgaon'),
  ('Ranisankail', 'Thakurgaon'),
  ('Ajmiriganj', 'Habiganj'),
  ('Baniachang', 'Habiganj'),
  ('Bahubal', 'Habiganj'),
  ('Chunarughat', 'Habiganj'),
  ('Habiganj Sadar', 'Habiganj'),
  ('Lakhai', 'Habiganj'),
  ('Madhabpur', 'Habiganj'),
  ('Nabiganj', 'Habiganj'),
  ('Shayestaganj', 'Habiganj'),
  ('Moulvibazar Sadar', 'Maulvibazar'),
  ('Barlekha', 'Maulvibazar'),
  ('Juri', 'Maulvibazar'),
  ('Kamalganj', 'Maulvibazar'),
  ('Kulaura', 'Maulvibazar'),
  ('Rajnagar', 'Maulvibazar'),
  ('Sreemangal', 'Maulvibazar'),
  ('Bishwamvarpur', 'Sunamganj'),
  ('Chhatak', 'Sunamganj'),
  ('Derai', 'Sunamganj'),
  ('Dharampasha', 'Sunamganj'),
  ('Dowarabazar', 'Sunamganj'),
  ('Jagannathpur', 'Sunamganj'),
  ('Jamalganj', 'Sunamganj'),
  ('Sulla', 'Sunamganj'),
  ('Sunamganj Sadar', 'Sunamganj'),
  ('Shanthiganj', 'Sunamganj'),
  ('Tahirpur', 'Sunamganj'),
  ('Sylhet Sadar', 'Sylhet'),
  ('Beanibazar', 'Sylhet'),
  ('Bishwanath', 'Sylhet'),
  ('Dakshin Surma', 'Sylhet'),
  ('Balaganj', 'Sylhet'),
  ('Companiganj', 'Sylhet'),
  ('Fenchuganj', 'Sylhet'),
  ('Golapganj', 'Sylhet'),
  ('Gowainghat', 'Sylhet'),
  ('Jointapur', 'Sylhet'),
  ('Kanaighat', 'Sylhet'),
  ('Zakiganj', 'Sylhet'),
  ('Nobigonj', 'Sylhet'),
  ('Eidgaon', 'Cox''s Bazar'),
  ('Madhyanagar', 'Sunamganj'),
  ('Dasar', 'Madaripur')
) as v(name, district_name)
join public.locations dd on dd.type = 'district' and dd.name = v.district_name
where not exists (
  select 1 from public.locations l where l.type = 'upazila' and l.name = v.name and l.parent_id = dd.id
);
