-- Machine Attendance, Phase 3 slice 3A (Architecture Baseline v1.1 §18, §21.2;
-- ADR 0033): schema foundation for the Windows Attendance Agent's identity.
-- Expand-only: two new tables and one view; nothing existing changes.
--
--   attendance_agent_activation_codes   one-time activation codes, stored as hashes
--   attendance_agents                   one row per Agent installation
--   attendance_agents_safe              School-facing view without verifier columns
--
-- Credential model (Baseline §18.1-18.2):
--   * Device communication keys never reach the cloud; nothing here stores them.
--   * The Agent generates its own random secret, a stable install_id and a
--     stable credential prefix. The cloud stores only a SHA-256 hash of the
--     verifier the Agent derives from that secret (credential_hash), plus the
--     previous hash and its deadline while a rotation overlaps. Rotation keeps
--     the prefix.
--   * Activation codes are stored as SHA-256 hashes; the plaintext code exists
--     only in the creating user's browser and on the Agent PC.
--
-- Access model:
--   * No client role may read a hash column. Column-level SELECT grants on the
--     base tables cover only non-secret columns, so `select *` or selecting a
--     hash fails for every client role, including Super Admin.
--   * RLS: School members (Attendance grant) and Super Admin read their rows.
--     Only Super Admin may insert or update directly (maintenance and test
--     fixtures); the normal writers are the Phase 6 definer RPCs (activation,
--     rotation, heartbeat, revocation), which are not part of this migration.
--   * The Agent lifecycle is revocation, not deletion: no application role,
--     Super Admin included, has a DELETE path on attendance_agents. Deleting a
--     School still removes its rows (FK cascade). Any other destructive
--     maintenance is a database-admin operation outside this schema API.
--     A consumed code and its Agent also protect each other from deletion.

-- ---------------------------------------------------------------------------
-- 1. Activation codes.
create table public.attendance_agent_activation_codes (
  id uuid primary key default gen_random_uuid(),
  school_id uuid not null references public.schools (id) on delete cascade
    default public.app_current_school_id(),
  code_hash text not null
    constraint attendance_agent_activation_codes_hash_format check (code_hash ~ '^[0-9a-f]{64}$'),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  consumed_by_agent_id uuid,
  revoked_at timestamptz,
  revoked_by uuid references public.profiles (id) on delete set null,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  constraint attendance_agent_activation_codes_hash_unique unique (code_hash),
  constraint attendance_agent_activation_codes_school_scoped unique (school_id, id),
  constraint attendance_agent_activation_codes_expiry_after_creation check (expires_at > created_at),
  -- consumed_at and the resulting Agent are recorded together, once.
  constraint attendance_agent_activation_codes_consumption_complete
    check ((consumed_at is null) = (consumed_by_agent_id is null)),
  constraint attendance_agent_activation_codes_consumed_before_expiry
    check (consumed_at is null or consumed_at <= expires_at),
  -- A code is either consumed or revoked, never both.
  constraint attendance_agent_activation_codes_consumed_or_revoked
    check (consumed_at is null or revoked_at is null)
);

comment on table public.attendance_agent_activation_codes is
  'One-time Attendance Agent activation codes (ADR 0033). Stores only a SHA-256 hash of each code. Consumed rows are kept as audit history.';
comment on column public.attendance_agent_activation_codes.code_hash is
  'SHA-256 (hex) of the activation code. The plaintext code is never stored. Not readable by any client role.';

-- Codes still usable (not consumed, not revoked), by School and expiry.
create index attendance_agent_activation_codes_open_idx
  on public.attendance_agent_activation_codes (school_id, expires_at)
  where consumed_at is null and revoked_at is null;

-- ---------------------------------------------------------------------------
-- 2. Agents.
create table public.attendance_agents (
  id uuid primary key default gen_random_uuid(),
  school_id uuid not null references public.schools (id) on delete cascade
    default public.app_current_school_id(),
  name text not null default '' check (char_length(name) <= 100),
  hostname text check (char_length(hostname) <= 255),
  -- Generated by the Agent before activation; the activation retry key.
  install_id uuid not null,
  -- Generated by the Agent; the lookup half of its bearer credential. Stable
  -- for the installation's lifetime, including across rotations.
  credential_prefix text not null
    constraint attendance_agents_prefix_format check (credential_prefix ~ '^[A-Za-z0-9]{8,32}$'),
  -- SHA-256 (hex) of the verifier the Agent derives from its local secret.
  credential_hash text not null
    constraint attendance_agents_credential_hash_format check (credential_hash ~ '^[0-9a-f]{64}$'),
  -- During a rotation, the old hash stays valid until previous_valid_until.
  previous_credential_hash text
    constraint attendance_agents_previous_hash_format check (previous_credential_hash ~ '^[0-9a-f]{64}$'),
  previous_valid_until timestamptz,
  activation_code_id uuid,
  status text not null default 'active' check (status in ('active', 'revoked')),
  agent_version text check (char_length(agent_version) <= 64),
  os_info text check (char_length(os_info) <= 255),
  activated_at timestamptz not null default now(),
  last_heartbeat_at timestamptz,
  last_health jsonb,
  revoked_at timestamptz,
  revoked_by uuid references public.profiles (id) on delete set null,
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attendance_agents_install_id_unique unique (install_id),
  constraint attendance_agents_credential_prefix_unique unique (credential_prefix),
  constraint attendance_agents_school_scoped unique (school_id, id),
  -- One Agent per activation code.
  constraint attendance_agents_activation_code_unique unique (activation_code_id),
  -- The activation code belongs to the same School.
  constraint attendance_agents_activation_code_same_school
    foreign key (school_id, activation_code_id)
    references public.attendance_agent_activation_codes (school_id, id),
  constraint attendance_agents_previous_hash_complete
    check ((previous_credential_hash is null) = (previous_valid_until is null)),
  constraint attendance_agents_previous_hash_differs
    check (previous_credential_hash is null or previous_credential_hash <> credential_hash),
  constraint attendance_agents_revocation_consistent
    check ((status = 'revoked') = (revoked_at is not null))
);

comment on table public.attendance_agents is
  'Windows Attendance Agent installations (ADR 0033). Revoked, never deleted in normal operation. Hash columns are not readable by any client role; read attendance_agents_safe.';
comment on column public.attendance_agents.credential_hash is
  'SHA-256 (hex) of the Agent''s credential verifier. The Agent''s secret is never stored. Not readable by any client role.';

create index attendance_agents_school_idx on public.attendance_agents (school_id);

-- The consumed code points at the Agent it activated, in the same School.
alter table public.attendance_agent_activation_codes
  add constraint attendance_agent_activation_codes_agent_same_school
    foreign key (school_id, consumed_by_agent_id)
    references public.attendance_agents (school_id, id),
  add constraint attendance_agent_activation_codes_agent_unique unique (consumed_by_agent_id);

-- ---------------------------------------------------------------------------
-- 3. Immutability.
--
-- An Agent's identity (School, install_id, credential prefix, creation) never
-- changes, its activation link is set once, and revocation is one-way.
-- updated_at is maintained here too.
create function public.attendance_agents_guard() returns trigger
language plpgsql set search_path = public as $$
begin
  if new.school_id is distinct from old.school_id then
    raise exception 'attendance_agents.school_id is immutable';
  end if;
  if new.install_id is distinct from old.install_id then
    raise exception 'attendance_agents.install_id is immutable';
  end if;
  if new.credential_prefix is distinct from old.credential_prefix then
    raise exception 'attendance_agents.credential_prefix is immutable';
  end if;
  if new.created_at is distinct from old.created_at or new.created_by is distinct from old.created_by
     or new.activated_at is distinct from old.activated_at then
    raise exception 'attendance_agents creation fields are immutable';
  end if;
  if old.activation_code_id is not null and new.activation_code_id is distinct from old.activation_code_id then
    raise exception 'attendance_agents.activation_code_id is immutable once set';
  end if;
  if old.revoked_at is not null and (new.revoked_at is distinct from old.revoked_at or new.status <> 'revoked') then
    raise exception 'a revoked Attendance Agent cannot be changed back';
  end if;
  new.updated_at := now();
  return new;
end $$;

create trigger attendance_agents_guard
  before update on public.attendance_agents
  for each row execute function public.attendance_agents_guard();

-- A code's School, hash, expiry and creation never change; consumption and
-- revocation are each recorded once and never undone.
create function public.attendance_agent_activation_codes_guard() returns trigger
language plpgsql set search_path = public as $$
begin
  if new.school_id is distinct from old.school_id or new.code_hash is distinct from old.code_hash
     or new.expires_at is distinct from old.expires_at or new.created_at is distinct from old.created_at
     or new.created_by is distinct from old.created_by then
    raise exception 'attendance_agent_activation_codes identity fields are immutable';
  end if;
  if old.consumed_at is not null and (new.consumed_at is distinct from old.consumed_at
     or new.consumed_by_agent_id is distinct from old.consumed_by_agent_id) then
    raise exception 'a consumed activation code cannot be changed';
  end if;
  if old.revoked_at is not null and (new.revoked_at is distinct from old.revoked_at
     or new.revoked_by is distinct from old.revoked_by) then
    raise exception 'a revoked activation code cannot be changed back';
  end if;
  return new;
end $$;

create trigger attendance_agent_activation_codes_guard
  before update on public.attendance_agent_activation_codes
  for each row execute function public.attendance_agent_activation_codes_guard();

-- ---------------------------------------------------------------------------
-- 4. Grants. Supabase's default privileges give client roles ALL on new
-- tables; replace that with explicit, column-limited grants.
revoke all on public.attendance_agents from anon, authenticated;
revoke all on public.attendance_agent_activation_codes from anon, authenticated;

-- Readable columns: everything except the hashes.
grant select (id, school_id, name, hostname, install_id, credential_prefix, previous_valid_until,
              activation_code_id, status, agent_version, os_info, activated_at, last_heartbeat_at,
              last_health, revoked_at, revoked_by, created_by, created_at, updated_at)
  on public.attendance_agents to authenticated;
grant select (id, school_id, expires_at, consumed_at, consumed_by_agent_id, revoked_at, revoked_by,
              created_by, created_at)
  on public.attendance_agent_activation_codes to authenticated;

-- Direct writes are for Super Admin only (enforced by RLS below). No DELETE on
-- Agents for any client role: an Agent is revoked, never deleted.
grant insert, update on public.attendance_agents to authenticated;
grant insert, update, delete on public.attendance_agent_activation_codes to authenticated;

-- ---------------------------------------------------------------------------
-- 5. RLS.
alter table public.attendance_agents enable row level security;
alter table public.attendance_agent_activation_codes enable row level security;

create policy "school members read attendance agents" on public.attendance_agents
  for select
  using (school_id = public.app_current_school_id() and (select public.app_module_granted('attendance')));
create policy "super admin reads attendance agents" on public.attendance_agents
  for select using (public.app_current_role() = 'super_admin');
create policy "super admin inserts attendance agents" on public.attendance_agents
  for insert with check (public.app_current_role() = 'super_admin');
create policy "super admin updates attendance agents" on public.attendance_agents
  for update
  using (public.app_current_role() = 'super_admin')
  with check (public.app_current_role() = 'super_admin');

create policy "school members read attendance agent activation codes" on public.attendance_agent_activation_codes
  for select
  using (school_id = public.app_current_school_id() and (select public.app_module_granted('attendance')));
create policy "super admin manages attendance agent activation codes" on public.attendance_agent_activation_codes
  for all
  using (public.app_current_role() = 'super_admin')
  with check (public.app_current_role() = 'super_admin');

-- ---------------------------------------------------------------------------
-- 6. School-facing view. security_invoker: it runs with the caller's
-- privileges, so the base table's RLS (own School, Attendance grant) applies,
-- and it only names columns the caller may already read.
create view public.attendance_agents_safe
  with (security_invoker = on) as
  select id, school_id, name, hostname, install_id, credential_prefix, status,
         agent_version, os_info, activated_at, last_heartbeat_at, last_health,
         previous_valid_until, activation_code_id,
         revoked_at, revoked_by, created_by, created_at, updated_at
  from public.attendance_agents;

comment on view public.attendance_agents_safe is
  'Non-secret Attendance Agent metadata for School members (security_invoker: base-table RLS applies).';

revoke all on public.attendance_agents_safe from anon, authenticated;
grant select on public.attendance_agents_safe to authenticated;
